[package]
name = "rlhcbfix"
version = "0.1.0"
authors = ["Sam Green <sam.green81@gmail.com>"]

[dependencies]
failure = "0.1.1"
structopt = "0.2"
winapi = { version = "0.3.4", features = ["handleapi", "tlhelp32", "realtimeapiset"] }
#widestring = "0.3.0"
ta = "0.1.0"
